---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "wallarm-sidecar.fullname" . }}
  annotations:
    {{ if and .Values.controller.admissionWebhook.certManager.enabled (not .Values.controller.admissionWebhook.secret.enabled) -}}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ template "wallarm-sidecar.fullname" . }}-admission
    {{- end }}
    {{- include "wallarm-sidecar.annotations" . | nindent 4 }}
    {{- with .Values.controller.admissionWebhook.extraAnnotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
    {{- with .Values.controller.admissionWebhook.extraLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
webhooks:
  - name: injector.sidecar.wallarm.io
    admissionReviewVersions: ["v1"]
    matchPolicy: Equivalent
    rules:
      - apiGroups: ["*"]
        apiVersions: ["v1"]
        operations:
          - CREATE
        resources:
          - pods
    objectSelector: {{- .Values.controller.admissionWebhook.objectSelector | toYaml | nindent 6 }}
    failurePolicy: {{ .Values.controller.admissionWebhook.failurePolicy | default "Fail" }}
    clientConfig:
      {{ if .Values.controller.admissionWebhook.secret.enabled -}}
      caBundle: {{ .Values.controller.admissionWebhook.secret.ca }}
      {{ end }}
      service:
        namespace: {{ .Release.Namespace | quote }}
        name: {{ include "wallarm-sidecar.fullname" . }}-controller
        port: {{ .Values.controller.service.port }}
        path: "/inject"
    sideEffects: None
