apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "wallarm-sidecar.fullname" . }}-controller
  annotations:
    {{- include "wallarm-sidecar.annotations" . | nindent 4 }}
    {{- with .Values.controller.extraAnnotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.controller.extraLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
data:
  config.yaml: |-
    settings:
      {{- toYaml .Values.config | nindent 6 }}
      wstore:
        host: {{ template "wallarm-sidecar.wstoreHost" . }}
        port: {{ template "wallarm-sidecar.wstorePort" . }}
      component:
        name: {{ template "wallarm-sidecar.componentName" . }}
        version: {{ .Chart.Version }}