apiVersion: v1
kind: Service
metadata:
  name: {{ template "wallarm-sidecar.fullname" . }}-controller
  annotations:
    {{- include "wallarm-sidecar.annotations" . | nindent 4 }}
    {{- with .Values.controller.extraAnnotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    {{- with .Values.controller.service.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.controller.extraLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.controller.service.type | default "ClusterIP" }}
  {{- with .Values.controller.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- if eq (.Values.controller.service.type | default "ClusterIP") "LoadBalancer" -}}
  {{- with .Values.controller.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.controller.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ . | toYaml | nindent 2 }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "wallarm-sidecar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  ports:
  - name: https
    port: {{ .Values.controller.service.port }}
    targetPort: https
    protocol: TCP
    {{- if has (.Values.controller.service.type | default "ClusterIP") (list "NodePort" "LoadBalancer") -}}
    {{- with .Values.controller.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
    {{- end }}
    {{- if semverCompare ">=1.20" .Capabilities.KubeVersion.Version }}
    appProtocol: https
    {{- end }}
  {{- if has (.Values.controller.service.type | default "ClusterIP") (list "NodePort" "LoadBalancer") }}
  {{- with .Values.controller.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- end }}
  {{- with .Values.controller.service.externalIPs }}
  externalIPs: {{- . | toYaml | nindent 2 }}
  {{- end }}
