{{- if .Values.postanalytics.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wallarm-sidecar.postanalytics.serviceAccountName" . }}
  annotations:
    {{- include "wallarm-sidecar.annotations" . | nindent 4 }}
    {{- with .Values.postanalytics.extraAnnotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    {{- with .Values.postanalytics.serviceAccount.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: postanalytics
    {{- with .Values.postanalytics.extraLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
{{- end -}}
