apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wallarm-sidecar.fullname" . }}-credentials
  annotations:
    {{- include "wallarm-sidecar.annotations" . | nindent 4 }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
type: Opaque
data:
  WALLARM_API_TOKEN: {{ .Values.config.wallarm.api.token | b64enc | quote }}
  WALLARM_API_HOST: {{ .Values.config.wallarm.api.host | b64enc | quote }}
  WALLARM_API_PORT: {{ .Values.config.wallarm.api.port | toString | b64enc | quote }}
  WALLARM_API_USE_SSL: {{ .Values.config.wallarm.api.useSSL | toString | b64enc | quote }}
  WALLARM_API_CA_VERIFY: {{ .Values.config.wallarm.api.caVerify | toString | b64enc | quote }}
  WALLARM_LABELS: {{ printf "group=%s" .Values.config.wallarm.api.nodeGroup | b64enc | quote }}
