{{- if and (not .Values.controller.admissionWebhook.certManager.enabled) (not .Values.controller.admissionWebhook.secret.enabled) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "wallarm-sidecar.fullname" . }}-admission-patch
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- include "wallarm-sidecar.annotations" . | nindent 4 }}
    {{- with .Values.controller.admissionWebhook.extraAnnotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
    {{- with .Values.controller.admissionWebhook.extraLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
{{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  # Alpha feature since k8s 1.12
  ttlSecondsAfterFinished: 0
{{- end }}
  template:
    metadata:
      name: {{ template "wallarm-sidecar.fullname" . }}-admission-patch
      annotations:
        {{- include "wallarm-sidecar.annotations" . | nindent 8 }}
        {{- with .Values.controller.admissionWebhook.extraAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      labels:
        {{- include "wallarm-sidecar.labels" . | nindent 8 }}
        app.kubernetes.io/component: admission-webhook
        {{- with .Values.controller.admissionWebhook.extraLabels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
    {{- end }}
      containers:
        - name: patch
          {{- with .Values.controller.admissionWebhook.patch.image }}
          image: {{ if .repository }}{{ .repository }}{{ else }}{{ .registry }}/{{ .image }}{{ end }}:{{ .tag }}{{ if .digest }}@{{ .digest }}{{ end }}
          {{- end }}
          imagePullPolicy: {{ .Values.controller.admissionWebhook.patch.image.pullPolicy }}
          args:
            - patch
            - --webhook-name={{ template "wallarm-sidecar.fullname" . }}
            - --namespace=$(POD_NAMESPACE)
            - --patch-validating=false
            - --secret-name={{ template "wallarm-sidecar.fullname" . }}-admission-tls
            - --patch-failure-policy={{ .Values.controller.admissionWebhook.failurePolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.controller.admissionWebhook.extraEnvs }}
            {{- toYaml .Values.controller.admissionWebhook.extraEnvs | nindent 12 }}
          {{- end }}
          {{- if .Values.controller.admissionWebhook.patchWebhookJob.securityContext }}
          securityContext: {{ toYaml .Values.controller.admissionWebhook.patchWebhookJob.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.controller.admissionWebhook.patchWebhookJob.resources }}
          resources: {{ toYaml .Values.controller.admissionWebhook.patchWebhookJob.resources | nindent 12 }}
          {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "wallarm-sidecar.fullname" . }}-admission
    {{- with .Values.controller.nodeSelector }}
      nodeSelector: {{ . | toYaml | nindent 8 }}
    {{- end }}
    {{- with .Values.controller.tolerations }}
      tolerations: {{ . | toYaml | nindent 8 }}
    {{- end }}
    {{- if .Values.controller.admissionWebhook.patch.securityContext }}
      securityContext: {{ toYaml .Values.controller.admissionWebhook.patch.securityContext | nindent 8 }}
    {{- end }}
{{- end }}
