apiVersion: v2
name: wallarm-sidecar
version: 4.6.1
appVersion: 4.6.2
description: Sidecar controller for Kubernetes. Injects sidecar proxy based on NGINX with Wallarm module and helper services.
home: https://github.com/wallarm/sidecar
icon: https://static.wallarm.com/wallarm-logo.svg
sources:
  - https://github.com/wallarm/sidecar
keywords:
  - sidecar
  - nginx
  - firewall
  - wallarm
maintainers:
  - name: Wallarm Support Team
    email: support@wallarm.com
type: application
engine: gotpl
kubeVersion: ">=1.19.16-0"
annotations:
  artifacthub.io/images: |
    - name: sidecar
      image: wallarm/sidecar:4.6.3-1
    - name: sidecar-controller
      image: wallarm/sidecar-controller:1.3.1
    - name: ingress-ruby
      image: wallarm/ingress-ruby:4.6.4-1
    - name: ingress-python
      image: wallarm/ingress-python:4.6.4-1
    - name: ingress-tarantool
      image: wallarm/ingress-tarantool:4.6.4-1
