apiVersion: v2
name: wallarm-sidecar
version: 5.3.7
appVersion: 5.3.7
description: Sidecar controller for Kubernetes. Injects sidecar proxy based on NGINX with Wallarm module and helper services.
home: https://github.com/wallarm/sidecar
icon: https://static.wallarm.com/wallarm-logo.svg
sources:
  - https://github.com/wallarm/sidecar
keywords:
  - sidecar
  - nginx
  - firewall
  - wallarm
maintainers:
  - name: Wallarm Support Team
    email: support@wallarm.com
type: application
engine: gotpl
kubeVersion: ">=1.19.16-0"
annotations:
  artifacthub.io/images: |
    - name: sidecar
      image: wallarm/sidecar:5.3.7
    - name: sidecar-controller
      image: wallarm/sidecar-controller:1.6.0
    - name: node-helpers
      image: wallarm/node-helpers:5.3.7
