config:
  sidecar:
    image:
      image: dmitriev/sidecar-proxy
      registry: quay.io
    containers:
      proxy:
        readinessProbeEnable: false

controller:
  image:
    image: dmitriev/sidecar-injector
    registry: quay.io
  replicaCount: 1