config:
  wallarm:
    api:
      token: WAGG4o/gxb/jt8ePWeCqnG8nmJPOOZnegUmfudeojBPGhe2wYPREOKNHAUkTHsFK
      host: audit.api.wallarm.com

controller:
  replicaCount: 1
  image:
    registry: quay.io
    image: dmitriev/sidecar-injector
    tag: "0.1.3"
