config:
  sidecar:
    containers:
      proxy:
        readinessProbe:
          initialDelaySeconds: 30
  wallarm:
    fallback: "off"

controller:
  replicaCount: 1
imagePullSecrets:
  - name: dockerhub-secret

postanalytics:
  init:
    extraEnvs:
      - name: WALLARM_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.uid
  supervisord:
    extraEnvs:
      - name: WALLARM_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.uid