# This workflow triggers if PR is opened, reopened, synchronize and closed to target branch 'main'
# 'Check' job skips execution of whole workflow if:
#   1. PR is closed and NOT merged
#   2. Source branch of PR is 'update_versions'
# 'Update versions' job triggers only if PR is closed and MERGED

name: Helm test

on:
  pull_request:
    branches: ['main']
    types: ['closed', 'opened', 'reopened', 'synchronize']
    paths:
      - 'helm/**'
      - '!helm/Chart.yaml'
      - '!helm/README.md'
      - '!helm/test/**'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    if: ${{ !contains(github.head_ref, 'update_versions') && !(github.event.action == 'closed' && github.event.pull_request.merged == false) }}
    outputs:
      ref: ${{ steps.check.outputs.ref }}
    steps:
      - name: Check
        id: check
        run: |
          if [ "${{ github.event.action }}" == "closed" ] && [ ${{ github.event.pull_request.merged }} == true ]; then
            echo "::set-output name=ref::${{ github.base_ref }}"
          else
            echo "::set-output name=ref::${{ github.head_ref }}"
          fi

  lint:
    name: Helm lint
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.check.outputs.ref }}

      - name: Helm lint
        run: |
          helm version
          helm lint helm/. --debug

  validate:
    name: Validate manifests
    env:
      KUBEVAL_SCHEMA_LOCATION: 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/'
    needs:
      - lint
      - check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 1.19-1.24
        kubeVersion:
          - 1.19.16
          - 1.20.15
          - 1.21.14
          - 1.22.11
          - 1.23.8
          - 1.24.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.check.outputs.ref }}

      - name: Helm template
        run: helm template helm/. > result-${{ matrix.kubeVersion }}.yaml --kube-version ${{ matrix.kubeVersion }} --debug

      - name: Kubeval
        uses: instrumenta/kubeval-action@master
        with:
          files: result-${{ matrix.kubeVersion }}.yaml
          version: ${{ matrix.kubeVersion }}
          ignore_missing_schemas: false

  test:
    name: Integration test
    needs:
      - validate
      - check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 1.19-1.24
        kubeVersion:
          - 1.19.16
          - 1.20.15
          - 1.21.12
          - 1.22.9
          - 1.23.6
          - 1.24.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.check.outputs.ref }}

      - name: Create cluster
        uses: helm/kind-action@v1.3.0
        with:
          verbosity: "0"
          wait: "240s"
          config: helm/test/kind/kind.yaml
          node_image: kindest/node:v${{ matrix.kubeVersion }}
          cluster_name: kind

      - name: Wait cluster
        run: |
          kubectl cluster-info
          kubectl wait --for=condition=Ready pods --all --timeout=180s -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Install Helm chart
        run: |
          set -x
          helm version
          helm install wallarm-sidecar ./helm -f helm/values.test.yaml \
            --set config.wallarm.api.token=${{ secrets.API_TOKEN }}
          kubectl wait --for=condition=Ready pods --all --timeout=5m0s
          kubectl describe pod -l app.kubernetes.io/component=postanalytics
          kubectl describe pod -l app.kubernetes.io/component=controller

      - name: Run test
        run: |
          kubectl apply -f kind/docker/manifests/init/pytest.yaml
          while [[ -z $(kubectl -n pytest get pods -o name) ]]; do
            sleep 1
          done
          kubectl -n pytest wait pods --all --for=condition=Ready
          POD_NAME=$(kubectl get pods -n pytest -o name | cut -d '/' -f 2)
          kubectl -n pytest exec -t ${POD_NAME} -- pytest -n 4 helm/test

  # Update version triggers if pull request closed and merged
  update_versions:
    name: Update versions
    needs: test
    if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true }}
    uses: wallarm/sidecar/.github/workflows/update_versions.yaml@main
