# This workflow triggers by sending POST request to https://api.github.com/repos/wallarm/sidecar/dispatches
# with the following body:
#  {
#    "event_type": "upstream_update",
#    "client_payload": {
#      "sidecar_update": bool,
#      "sidecar_tag": "string",
#      "upstream_update": bool,
#      "upstream_tag": "string"
#    }
#  }

name: Upstream update handler

on:
  repository_dispatch:
    types: [upstream_update]

jobs:
  preparation:
    name: Preparation
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.upstream_update || github.event.client_payload.sidecar_update }}
    outputs:
      helm_args: ${{ steps.compute_helm_args.outputs.helm_args }}
    steps:
      - name: Payload sanity check
        run: |
          if [ ${{ github.event.client_payload.upstream_update }} = true ]; then
            echo "Upstream update was requested"
            if [ -z ${{ github.event.client_payload.upstream_tag }} ]; then
              echo "Upstream tag is empty! It should be set in 'client_payload.upstream_tag' property. \nPayload sanity check failed! Exiting ..."
              exit 1
            else
              echo "OK"
            fi
          fi
      
          if [ ${{ github.event.client_payload.sidecar_update }} = true ]; then
            echo "Sidecar update was requested"
            if [ -z ${{ github.event.client_payload.sidecar_tag }} ]; then
              echo "Sidecar tag is empty! It should be set in 'client_payload.sidecar_tag' property. \nPayload sanity check failed! Exiting ..."
              exit 1
            else
              echo "OK"
            fi
          fi
      
          echo "Payload sanity check PASSED"

      - name: Compute Helm arguments
        id: compute_helm_args
        run: |
          HELM_ARGS=""
          if [ ${{ github.event.client_payload.upstream_update }} = true ]; then
            UPSTREAM_TAG=${{ github.event.client_payload.upstream_tag }}
            HELM_ARGS+="\
              --set helper.image.tag=${UPSTREAM_TAG}"
            echo "HELM_ARGS: ${HELM_ARGS}"
          fi
          
          if [ ${{ github.event.client_payload.sidecar_update }} = true ]; then
            SIDECAR_TAG=${{ github.event.client_payload.sidecar_tag }}
            HELM_ARGS+=" --set config.sidecar.image.tag=${SIDECAR_TAG}"
          fi
          
          echo "helm_args=${HELM_ARGS}" >> $GITHUB_OUTPUT

  test:
    name: Test
    needs: preparation
    uses: wallarm/sidecar/.github/workflows/test.yaml@main
    secrets:
      API_TOKEN: ${{ secrets.API_TOKEN }}
    with:
      ref: "main"
      run_lint: false
      run_validate: false
      run_test: true
      run_ct: true
      helm_args: ${{ needs.preparation.outputs.helm_args }}
      load_artifact: false

  update_versions:
    name: Update versions
    needs: test
    uses: wallarm/sidecar/.github/workflows/update_versions.yaml@main
    secrets:
      HELM_PUBLISH_TOKEN: ${{ secrets.HELM_PUBLISH_TOKEN }}
      NEWS_API_CREDS: ${{ secrets.NEWS_API_CREDS }}
    with:
      upstream_update: ${{ github.event.client_payload.upstream_update }}
      upstream_tag: ${{ github.event.client_payload.upstream_tag }}
      sidecar_update: ${{ github.event.client_payload.sidecar_update }}
      sidecar_tag: ${{ github.event.client_payload.sidecar_tag }}