# This workflow triggers by sending POST request to https://api.github.com/repos/wallarm/sidecar/dispatches
# with the following body:
#  {
#    "event_type": "upstream_update",
#    "client_payload": {
#      "sidecar_update": bool,
#      "sidecar_tag": "string",
#      "upstream_update": bool,
#      "upstream_tag": "string"
#    }
#  }

name: Upstream update handler

on:
  repository_dispatch:
    types: [upstream_update]

jobs:
  check:
    name: Payload sanity check
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.upstream_update || github.event.client_payload.sidecar_update }}
    steps:
      - name: Payload sanity check
        run: |
          if [ ${{ github.event.client_payload.upstream_update }} = true ]; then
            echo "Upstream update was requested"
            if [ -z ${{ github.event.client_payload.upstream_tag }} ]; then
              echo "Upstream tag is empty! It should be set in 'client_payload.upstream_tag' property. \nPayload sanity check failed! Exiting ..."
              exit 1
            else
              echo "OK"
            fi
          fi
      
          if [ ${{ github.event.client_payload.sidecar_update }} = true ]; then
            echo "Sidecar update was requested"
            if [ -z ${{ github.event.client_payload.sidecar_tag }} ]; then
              echo "Sidecar tag is empty! It should be set in 'client_payload.sidecar_tag' property. \nPayload sanity check failed! Exiting ..."
              exit 1
            else
              echo "OK"
            fi
          fi
      
          echo "Payload sanity check PASSED"

  test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Prepare Helm arguments
        run: |
          HELM_ARGS=""
          if [ ${{ github.event.client_payload.upstream_update }} = true ]; then
            UPSTREAM_TAG=${{ github.event.client_payload.upstream_tag }}
            HELM_ARGS+="\
              --set postanalytics.addnode.image.tag=${UPSTREAM_TAG} \
              --set postanalytics.exportenv.image.tag=${UPSTREAM_TAG} \
              --set postanalytics.cron.image.tag=${UPSTREAM_TAG} \
              --set postanalytics.tarantool.image.tag=${UPSTREAM_TAG} \
              --set postanalytics.heartbeat.image.tag=${UPSTREAM_TAG} \
              --set postanalytics.appstructure.image.tag=${UPSTREAM_TAG}"
            echo "HELM_ARGS: ${HELM_ARGS}"
          fi
          
          if [ ${{ github.event.client_payload.sidecar_update }} = true ]; then
            SIDECAR_TAG=${{ github.event.client_payload.sidecar_tag }}
            HELM_ARGS+=" --set config.sidecar.image.tag=${SIDECAR_TAG}"
          fi
          
          echo "HELM_ARGS=${HELM_ARGS}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Create cluster
        uses: helm/kind-action@v1.3.0
        with:
          verbosity: "0"
          wait: "240s"
          config: helm/test/kind/kind.yaml
          node_image: kindest/node:v1.24.2
          cluster_name: kind

      - name: Wait cluster
        run: |
          kubectl cluster-info
          kubectl wait --for=condition=Ready pods --all --timeout=180s -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Install Helm chart
        run: |
          helm version
          helm install wallarm-sidecar helm/. -f helm/values.test.yaml ${HELM_ARGS} \
            --set config.wallarm.api.token=${{ secrets.API_TOKEN }} \
            --timeout 5m0s \
            --wait
          kubectl wait --for=condition=Ready pods --all --timeout=30s
          kubectl get all
          kubectl describe pod -l app.kubernetes.io/component=controller
          kubectl describe pod -l app.kubernetes.io/component=postanalytics

      - name: Run test
        run: |
          kubectl apply -f kind/docker/manifests/init/pytest.yaml
          kubectl -n pytest wait pods --all --for=condition=Ready
          POD_NAME=$(kubectl get pods -n pytest -o name | cut -d '/' -f 2) 
          kubectl -n pytest exec -t ${POD_NAME} -- pytest -n 4 helm/test

  update_versions:
    name: Update versions
    needs: test
    uses: wallarm/sidecar/.github/workflows/update_versions.yaml@main
    with:
      upstream_update: ${{ github.event.client_payload.upstream_update }}
      upstream_tag: ${{ github.event.client_payload.upstream_tag }}
      sidecar_update: ${{ github.event.client_payload.sidecar_update }}
      sidecar_tag: ${{ github.event.client_payload.sidecar_tag }}